# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
#
# Hardware:
#
# CPU:     Intel Core i5-9600K
# GPU:     NVIDIA GeForce RTX 4060
# RAM:     16 GB
# Storage: NVMe
#
# Root:
#   UUID=e94a0e96-2453-47d9-9369-638602758914
#
# EFI:
#   UUID=4987-B75B
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ============================================================
  # INITRD
  # ============================================================

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [
  ];

  # ============================================================
  # KERNEL
  # ============================================================

  boot.kernelModules = [
    "kvm-intel"
  ];

  boot.extraModulePackages = [
  ];

  # ============================================================
  # ROOT
  # ============================================================

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e94a0e96-2453-47d9-9369-638602758914";

    fsType = "ext4";
  };

  # ============================================================
  # EFI
  # ============================================================

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4987-B75B";

    fsType = "vfat";

    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # ============================================================
  # SWAP
  # ============================================================

  swapDevices = [
  ];

  # ============================================================
  # NETWORK
  # ============================================================

  networking.useDHCP =
    lib.mkDefault true;

  # ============================================================
  # PLATFORM
  # ============================================================

  nixpkgs.hostPlatform =
    lib.mkDefault "x86_64-linux";

  # ============================================================
  # MICROCODE
  # ============================================================

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault
    config.hardware.enableRedistributableFirmware;
}
